Repository algosup/2024-2025-project-2-serious-game-team-6, pull requests merged in 2024-12, with the labels that each got.

#20 Quality assurance testPlan
  Documents/QualityAssurance/testPlan.md
Labels: documentation, enhancement

#25 Merging corrected bugs and typo
  Game/3d-game-project/2D/Interaction 2D/Interaction/playerInteractor2d.gd
  Game/3d-game-project/2D/Scenes/HUB/Scientist.tscn
  Game/3d-game-project/2D/Scenes/HUB/background.tscn
  Game/3d-game-project/2D/Scenes/HUB/collisionShape2d.gd
  Game/3d-game-project/2D/Scenes/HUB/globe.gd
  Game/3d-game-project/2D/Scenes/HUB/globe.tscn
  Game/3d-game-project/2D/Scenes/HUB/scientist.gd
  Game/3d-game-project/2D/Scenes/HUB/teleporter2d.gd
  Game/3d-game-project/2D/Scenes/HUB/teleporter2d.tscn
  Game/3d-game-project/2D/Scenes/HUB/wall.tscn
  Game/3d-game-project/2D/Scenes/House/cabin.gd
  Game/3d-game-project/2D/Scenes/House/cabin.tscn
  Game/3d-game-project/2D/Scenes/House/cabinBackgound.tscn
  Game/3d-game-project/2D/Scenes/House/cabinWall.tscn
  Game/3d-game-project/2D/Scenes/Player/player.gd
  Game/3d-game-project/2D/Scenes/Player/player.tscn
  Game/3d-game-project/2D/Scenes/ReactorPowerPlant/powerPlant2d.tscn
  Game/3d-game-project/2D/Scenes/ReactorPowerPlant/reactorBackground.tscn
  Game/3d-game-project/2D/Scenes/ReactorPowerPlant/reactorCollision.tscn
  Game/3d-game-project/2D/Scenes/TextboxWithPortrait/customTextboxWithPortrait.tscn
  Game/3d-game-project/2D/Scenes/TextboxWithPortrait/speakerPortraitTextboxLayer.gd
  Game/3d-game-project/2D/Scenes/cabin.tscn
  Game/3d-game-project/2D/Scenes/house.tscn
  Game/3d-game-project/2D/Scenes/main.tscn
  Game/3d-game-project/2D/Scenes/scientistIcon.tscn
  Game/3d-game-project/2D/Script/player.gd
  Game/3d-game-project/3D/Maps/Forest/Teleporter.tscn
  Game/3d-game-project/3D/Maps/Forest/forest.tscn
  Game/3d-game-project/3D/Maps/Forest/house.gd
  Game/3d-game-project/3D/Maps/Forest/house.tscn
  Game/3d-game-project/3D/Maps/Forest/teleporter.gd
  Game/3d-game-project/3D/Maps/ReactorPowerPlant/nuclearReactor.tscn
  Game/3d-game-project/3D/Maps/Ressource/allCubes2.tres
  Game/3d-game-project/3D/main3d.gd
  Game/3d-game-project/3D/main3d.tscn
  Game/3d-game-project/GameController.tscn
  Game/3d-game-project/README.md
  Game/3d-game-project/Sprite/HUB/teleporter.png.import
  Game/3d-game-project/Sprite/Player/Jump/Left-jumping-Sheet.png
  Game/3d-game-project/Sprite/Player/Jump/Left-jumping-Sheet.png.import
  Game/3d-game-project/gamecontroller.gd
  Game/3d-game-project/project.godot
Labels: enhancement, code

#30 merge user manual pdf + mk + images
  Manuals/User manual.md
  Manuals/User manual.pdf
  Manuals/image/Forest.png
  Manuals/image/Game manual.png
  Manuals/image/Hub.png
  Manuals/image/Protagonist.png
  Manuals/image/Scientist.png
  Manuals/image/Side view.png
  Manuals/image/Top view.png
  Manuals/manuals.md
Labels: documentation

#35 Management - Adding weekly report 6 to the main.
  Documents/Management/WeeklyReports/cumulative.md
  Documents/Management/WeeklyReports/week6.md
Labels: documentation, enhancement

#37 Management
  README.md
  SECURITY.md
Labels: documentation, enhancement

#38 fix when trying to get back to the hub after activating the reactor p…
  Game/3d-game-project/3D/Maps/Ressource/allCubes2.tres
  Game/3d-game-project/3D/Maps/Ressource/cubesNuclearReactor.tres
  Game/3d-game-project/3D/Object/Interaction/playerInteractor.gd
  Game/3d-game-project/Sprite/Cabin/forestcabinbackground.png.import
  Game/3d-game-project/Sprite/Cabin/forestcabincollision.png.import
  Game/3d-game-project/gameController.gd
Labels: bug, enhancement, code

#39 updating versions
  README.md
  SECURITY.md
Labels: documentation, enhancement

#40 Fixed crashing issues
  Game/3d-game-project/3D/Object/Interaction/playerInteractor.gd
  Game/3d-game-project/gameController.gd
Labels: bug, enhancement, code

#41 updating versions
  README.md
  SECURITY.md
Labels: documentation, enhancement

#42 Management
  Documents/Management/WeeklyReports/cumulative.md
  Documents/Management/WeeklyReports/week7.md
  Documents/Management/managementArtifact.md
Labels: documentation, enhancement
